# Generated by Django 4.2.10 on 2024-02-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma_api', '0003_plants_negative_neighbour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='negative_neighbour',
            new_name='negative_neighbours',
        ),
        migrations.RenameField(
            model_name='plants',
            old_name='positive_neighbour',
            new_name='positive_neighbours',
        ),
    ]
