# Generated by Django 4.2.10 on 2024-02-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma_api', '0005_month_soil_remove_plants_plant_month_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='month',
            managers=[
            ],
        ),
    ]
