# Generated by Django 4.2.10 on 2024-02-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma_api', '0006_alter_month_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Month',
            new_name='Months',
        ),
    ]
