# Generated by Django 4.2.10 on 2024-02-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma_api', '0007_rename_month_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='plant_month_id',
        ),
        migrations.AddField(
            model_name='plants',
            name='harvest_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perma_api.months'),
        ),
        migrations.AddField(
            model_name='plants',
            name='plant_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perma_api.months'),
        ),
    ]
